### ISSUE TITLE
[BUG] Receiving CUDA error: invalid argument using pytorch 2.7 with deepspeed 0.16.4 with Cuda 12.8

### ISSUE THREAD

**Issue by rpgmaker** [deepspeedai/DeepSpeed#7150]
**Describe the bug**
I am currently not able to run deepspeed latest version (0.16.4) with cuda 12.8 using pytorch 2.7. I am receiving the following error stack:
GPU: 3090 TI FE
```
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**To Reproduce**

Model Name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B

Use deepspeed config:

```
{
    "train_batch_size": 1,
    "gradient_accumulation_steps": 1,
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "fp16": {
        "enabled": true
    }
}
```

**Expected behavior**
I expect it to be able to run and allow me to train the model without getting CUDA error: invalid argument

**ds_report output**

```
[2025-03-18 20:48:02,997] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
 [WARNING]  FP Quantizer is using an untested triton version (3.2.0), only 2.3.(0, 1) and 3.0.0 are known to be compatible with these kernels
fp_quantizer ........... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
gds .................... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.7
 [WARNING]  using untested triton version (3.2.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/xxxx/lib/python3.12/site-packages/torch']
torch version .................... 2.7.0.dev20250309+cu128
deepspeed install path ........... ['/xxxx/lib/python3.12/site-packages/deepspeed']
deepspeed info ................... 0.16.4, unknown, unknown
torch cuda version ............... 12.8
torch hip version ................ None
nvcc version ..................... 12.8
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
shared memory (/dev/shm) size .... 61.66 GB

```
**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: Ubuntu 24.10
 - GPU count and types: 3090 TI FE 1
 - Interconnects : N/A
 - Python version: 3.12.7

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else? No

**Docker context**
Are you using a specific docker image that you can share? No

**Additional context**
N/A

**Comment by hwchen2017** [comment]
Hi @rpgmaker , can you shared the full error message you get to help us identify the cause? Thanks!

**Comment by rpgmaker** [comment]
Sure, here is the full stacktrace

```
[2025-03-19 14:54:53,885] [INFO] [stage_1_and_2.py:152:__init__] Round robin gradient partitioning: False
[rank0]: Traceback (most recent call last):
[rank0]:   File "/xxxxxx/main.py", line 41, in <module>
[rank0]:     run()
[rank0]:   File "/xxxxxx/main.py", line 36, in run
[rank0]:     setup_runner_qwen_1_5B()
[rank0]:   File "/xxxxxx/main.py", line 15, in setup_runner_qwen_1_5B
[rank0]:     runner.run(epoch=50)
[rank0]:   File "/xxxxxx/runner.py", line 47, in run
[rank0]:     self.trainer.train(epoch)
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 39, in train
[rank0]:     self.__setup()
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 73, in __setup
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 317, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1385, in _configure_optimizer
[rank0]:     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1643, in _configure_zero_optimizer
[rank0]:     optimizer = DeepSpeedZeroOptimizer(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 407, in __init__
[rank0]:     weights_partition = get_accelerator().pin_memory(weights_partition)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "xxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
[rank0]:     return tensor.pin_memory()
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W319 14:54:59.544769873 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

**Comment by hwchen2017** [comment]
Can you rerun the script after setting the environment variable `CUDA_LAUNCH_BLOCKING=1` by 
```
export CUDA_LAUNCH_BLOCKING=1
```
and then share the full stack trace? Thanks!

**Comment by rpgmaker** [comment]
Sure here is the new stacktrace with the env enabled.

```
[2025-03-19 18:52:01,562] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
[2025-03-19 18:52:07,164] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-19 18:52:07,165] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-19 18:52:07,165] [INFO] [comm.py:673:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2025-03-19 18:52:07,223] [INFO] [comm.py:728:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=10.0.0.246, master_port=29500
[2025-03-19 18:52:07,223] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-19 18:52:07,243] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[2025-03-19 18:52:07,344] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/xxxxxx/.cache/torch_extensions/py312_cu128 as PyTorch extensions root...
Emitting ninja build file /home/xxxxxx/.cache/torch_extensions/py312_cu128/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 2.1535685062408447 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000020, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2025-03-19 18:52:10,568] [INFO] [logging.py:128:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2025-03-19 18:52:10,568] [INFO] [logging.py:128:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2025-03-19 18:52:10,574] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2025-03-19 18:52:10,574] [INFO] [utils.py:59:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2025-03-19 18:52:10,574] [INFO] [logging.py:128:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2025-03-19 18:52:10,574] [INFO] [stage_1_and_2.py:149:__init__] Reduce bucket size 200000000
[2025-03-19 18:52:10,574] [INFO] [stage_1_and_2.py:150:__init__] Allgather bucket size 200000000
[2025-03-19 18:52:10,574] [INFO] [stage_1_and_2.py:151:__init__] CPU Offload: True
[2025-03-19 18:52:10,574] [INFO] [stage_1_and_2.py:152:__init__] Round robin gradient partitioning: False
[rank0]: Traceback (most recent call last):
[rank0]:   File "/xxxxxx/main.py", line 41, in <module>
[rank0]:     run()
[rank0]:   File "/xxxxxx/main.py", line 36, in run
[rank0]:     setup_runner_qwen_1_5B()
[rank0]:   File "/xxxxxx/main.py", line 15, in setup_runner_qwen_1_5B
[rank0]:     runner.run(epoch=50)
[rank0]:   File "/xxxxxx/runner.py", line 47, in run
[rank0]:     self.trainer.train(epoch)
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 39, in train
[rank0]:     self.__setup()
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 73, in __setup
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 317, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1385, in _configure_optimizer
[rank0]:     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1643, in _configure_zero_optimizer
[rank0]:     optimizer = DeepSpeedZeroOptimizer(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 407, in __init__
[rank0]:     weights_partition = get_accelerator().pin_memory(weights_partition)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/xxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
[rank0]:     return tensor.pin_memory()
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W319 18:52:15.078933979 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

**Comment by hwchen2017** [comment]
It appears that `pin_memory()` leads to this error. Can you try `pin_memory: false` to see if it can solve this problem?
Memory pinning can incur high memory consumption and cause memory allocation error. See here: #3481

**Comment by rpgmaker** [comment]
I tried to use the pin_memory: false and still end up with same issue.

config:

```
{
    "train_batch_size": 1,
    "gradient_accumulation_steps": 1,
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": false
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "fp16": {
        "enabled": true
    }
}
```


error trace:

```
[2025-03-21 17:51:00,755] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
[2025-03-21 17:51:06,216] [INFO] [logging.py:128:log_dist] [Rank -1] DeepSpeed info: version=0.16.4, git-hash=unknown, git-branch=unknown
[2025-03-21 17:51:06,216] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-03-21 17:51:06,216] [INFO] [comm.py:673:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2025-03-21 17:51:06,275] [INFO] [comm.py:728:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=10.0.0.246, master_port=29500
[2025-03-21 17:51:06,275] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-03-21 17:51:06,295] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[2025-03-21 17:51:06,403] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/xxxxxx/.cache/torch_extensions/py312_cu128 as PyTorch extensions root...
Emitting ninja build file /home/xxxxxx/.cache/torch_extensions/py312_cu128/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 2.176302909851074 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000020, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2025-03-21 17:51:09,684] [INFO] [logging.py:128:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2025-03-21 17:51:09,684] [INFO] [logging.py:128:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2025-03-21 17:51:09,689] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2025-03-21 17:51:09,689] [INFO] [utils.py:59:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2025-03-21 17:51:09,689] [INFO] [logging.py:128:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2025-03-21 17:51:09,689] [INFO] [stage_1_and_2.py:149:__init__] Reduce bucket size 200000000
[2025-03-21 17:51:09,689] [INFO] [stage_1_and_2.py:150:__init__] Allgather bucket size 200000000
[2025-03-21 17:51:09,689] [INFO] [stage_1_and_2.py:151:__init__] CPU Offload: True
[2025-03-21 17:51:09,689] [INFO] [stage_1_and_2.py:152:__init__] Round robin gradient partitioning: False
[rank0]: Traceback (most recent call last):
[rank0]:   File "/xxxxxx/main.py", line 41, in <module>
[rank0]:     run()
[rank0]:   File "/xxxxxx/main.py", line 36, in run
[rank0]:     setup_runner_qwen_1_5B()
[rank0]:   File "/xxxxxx/main.py", line 15, in setup_runner_qwen_1_5B
[rank0]:     runner.run(epoch=50)
[rank0]:   File "/xxxxxx/runner.py", line 47, in run
[rank0]:     self.trainer.train(epoch)
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 39, in train
[rank0]:     self.__setup()
[rank0]:   File "/xxxxxx/trainer/deepspeed/deepspeed_trainer.py", line 73, in __setup
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 317, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1385, in _configure_optimizer
[rank0]:     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1643, in _configure_zero_optimizer
[rank0]:     optimizer = DeepSpeedZeroOptimizer(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 407, in __init__
[rank0]:     weights_partition = get_accelerator().pin_memory(weights_partition)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
[rank0]:     return tensor.pin_memory()
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W321 17:51:14.766289001 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

**Comment by hwchen2017** [comment]
Hi @tjruwase , can you have a look at it?  Related PR: #4131

**Comment by tjruwase** [comment]
@rpgmaker, can you please share your full repro steps, so I can try on my side. I see that torch has changed `pin_memory()` behavior. 

Also, can you report the output of the following
1. `python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1024, device='cuda'))"`
2. `python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1024, device='cpu'))" `

**Comment by rpgmaker** [comment]
Sure, let me work on it and i will provide the steps with examples. Thanks

**Comment by rpgmaker** [comment]
Below is the runs for both the CPU and the GPU runs for torch, It seem the cpu version did not fail
```
python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1024, device='cuda'))"

output:
[2025-03-22 12:52:09,315] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
    return tensor.pin_memory()
           ^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot pin 'torch.cuda.FloatTensor' only dense CPU tensors can be pinned
```


```
python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1024, device='cpu'))" 
[2025-03-22 12:53:15,468] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
```

for full repo, use the following steps:

- Create python env
- Make sure to have Cuda 12.8 installed
- Run `pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`
- install the following requirement
```
deepspeed
datasets
transformers
sentence_transformers
mpi4py
```
- download the following py code example to run the training - https://gist.github.com/rpgmaker/5e35561682c3e6cdd4b802a9127cfb9d
- run it

**Comment by tjruwase** [comment]
I am unsure the best way to proceed. Below is my ds_report with some slight differences to your original post.
```bash
DeepSpeed general environment info:
torch install path ............... ['/py_venv/torch_2_cuda/lib/python3.12/site-packages/torch']
torch version .................... 2.8.0.dev20250322+cu128
deepspeed install path ........... ['/py_venv/torch_2_cuda/lib/python3.12/site-packages/deepspeed']
deepspeed info ................... 0.16.4, unknown, unknown
torch cuda version ............... 12.8
torch hip version ................ None
nvcc version ..................... 12.8
deepspeed wheel compiled w. ...... torch 2.8, cuda 12.8
```

**Comment by tjruwase** [comment]
> File "/home/xxxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
>     return tensor.pin_memory()

@rpgmaker, can you try changing the above code to `return tensor.cpu().pin_memory()`

**Comment by rpgmaker** [comment]
I tried using the changes with .cpu().pin_memory() and ended up with same errors

```
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 407, in __init__
[rank0]:     weights_partition = get_accelerator().pin_memory(weights_partition)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
[rank0]:     return tensor.cpu().pin_memory()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: **CUDA error: invalid argument**
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by tjruwase** [comment]
That is very strange. Can you try printing `tensor.dtype`, `tensor.shape` and `tensor.device` before the `pin_memory()` call?

**Comment by rpgmaker** [comment]
Here is the result below.

```
tensor.dtype:  torch.float32
tensor.shape:  torch.Size([1776255488])
tensor.device:  cpu
```

code changes:

```
def pin_memory(self, tensor, align_bytes=1):
        print("tensor.dtype: ", tensor.dtype)
        print("tensor.shape: ", tensor.shape)
        print("tensor.device: ", tensor.device)
        return tensor.cpu().pin_memory()
```

ds_config:

```
ds_config = {
        "train_batch_size": batch_size,
        "gradient_accumulation_steps": 1,
        "optimizer": {
            "type": "AdamW",
            "params": {
                "lr": learning_rate
            }
        },
        "bf16": {
            "enabled": torch.cuda.is_available()
        },
        "fp16": {
            "enabled": False
        },
        "zero_optimization": {
            "stage": 2, # Use stage 2 for memory efficiency
            "offload_optimizer": {
                "device": "cpu",
                "pin_memory": False
            },
            "allgather_partitions": True,
            "allgather_bucket_size": 2e8,
            "overlap_comm": True,
            "reduce_scatter": True,
            "reduce_bucket_size": 2e8,
            "contiguous_gradients": True
        }
    }
```

**Comment by tjruwase** [comment]
> tensor.dtype:  torch.float32
> tensor.shape:  torch.Size([1776255488])
> tensor.device:  cpu

@rpgmaker, thanks. Those are expected results and does not explain the error. I don't have a 3090 TI FE to try this on.  Can you retry the following now adjusted for tensor size?

`python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1776255488, device='cpu'))"`

**Comment by rpgmaker** [comment]
This is the result. it seem the allocation/pinning the memory is the issue:

```
python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1776255488, device='cpu'))"
[2025-03-23 11:54:42,621] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
tensor.dtype:  torch.float32
tensor.shape:  torch.Size([1776255488])
tensor.device:  cpu
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxxxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 296, in pin_memory
    return tensor.cpu().pin_memory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by tjruwase** [comment]
@rpgmaker, that is interesting. Maybe the tensor size is the cause, since we already saw that 1024 size worked. Can you test a sweep of tensor sizes starting from 1024, and doubling to see the failure point?

**Comment by tjruwase** [comment]
> "offload_optimizer": {
>                 "device": "cpu",
>                 "pin_memory": False

One workaround is to control this particular pinning by `pin_memory` in the ds_config. So to unblock you, please try changing the following condition to `if self.cpu_offload_pin_memory:`

https://github.com/deepspeedai/DeepSpeed/blob/1ca83a6bb9f3fffdb98c94093ab48605294241ae/deepspeed/runtime/zero/stage_1_and_2.py#L406-L407

**Comment by rpgmaker** [comment]
Thanks, will give it a try and let you know the results.

**Comment by rpgmaker** [comment]
> cpu_offload_pin_memory

Using this option actually cause my vscode to crash.

**Comment by rpgmaker** [comment]
@tjruwase  I run the memory test to see how much i can allocate and it failed here

```
tensor.dtype:  torch.float32
tensor.shape:  torch.Size([268493824])
tensor.device:  cpu
Traceback (most recent call last):
  File "/home/xxxxxxxx/test_tensor.py", line 8, in <module>
    get_accelerator().pin_memory(torch.empty(start * increase, device='cpu'))
  File "/home/xxxxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 296, in pin_memory
    return tensor.cpu().pin_memory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by rpgmaker** [comment]
Here is the code snippet for the test

```
import torch; 
from deepspeed.accelerator import get_accelerator; 

start = 1024
increase = 1

while True:
    get_accelerator().pin_memory(torch.empty(start * increase, device='cpu'))
    increase += 100
```

**Comment by tjruwase** [comment]
> > if self.cpu_offload:
> > weights_partition = get_accelerator().pin_memory(weights_partition)
> 
> Using this option actually cause my vscode to crash.

That is odd. What happens if you comment out the code?

**Comment by tjruwase** [comment]
> Here is the code snippet for the test
> 
> ```
> import torch; 
> from deepspeed.accelerator import get_accelerator; 
> 
> start = 1024
> increase = 1
> 
> while True:
>     get_accelerator().pin_memory(torch.empty(start * increase, device='cpu'))
>     increase += 100
> ```

Can you further reduce this to?

```python
import torch; 

start = 1024
increase = 1

while True:
    torch.empty(start * increase, device='cpu').pin_memory()
    increase += 100
```

**Comment by rpgmaker** [comment]
Switching the code to just torch.empty produces the following result:

```
Traceback (most recent call last):
  File "/home/xxxxxxx/test_tensor.py", line 7, in <module>
    torch.empty(start * increase, device='cpu')
RuntimeError: [enforce fail at alloc_cpu.cpp:119] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 141011357696 bytes. Error code 12 (Cannot allocate memory)
```

**Comment by rpgmaker** [comment]
@tjruwase with regards to commenting out the code. it started printing the epochs and was training but then crashed at the end of it. when trying to run the test phase

![Image](https://github.com/user-attachments/assets/bac92bfe-4c52-4ca4-9704-2a8efa14d7bd)

**Comment by tjruwase** [comment]
>     torch.empty(start * increase, device='cpu')
> RuntimeError: [enforce fail at alloc_cpu.cpp:119] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 141011357696 bytes. Error code 12 (Cannot allocate memory)
> ```

How DRAM do you have? 141011357696 bytes is ~141GB. So that might explain the error.

**Comment by tjruwase** [comment]
> File "/home/xxxxxxx/test_tensor.py", line 7, in <module>
>     torch.empty(start * increase, device='cpu')

Did you remove the `pin_memory()` in your test?

**Comment by rpgmaker** [comment]
> > File "/home/xxxxxxx/test_tensor.py", line 7, in 
> > torch.empty(start * increase, device='cpu')
> 
> Did you remove the `pin_memory()` in your test?

Yes, I did. This is the code that i used

```
import torch; 

start = 1024
increase = 1

while True:
    torch.empty(start * increase, device='cpu')
    increase += 100
```

**Comment by rpgmaker** [comment]
> > ```
> > torch.empty(start * increase, device='cpu')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > RuntimeError: [enforce fail at alloc_cpu.cpp:119] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 141011357696 bytes. Error code 12 (Cannot allocate memory)
> 
> How DRAM do you have? 141011357696 bytes is ~141GB. So that might explain the error.

I have about 141GB (132.4 GB for RAM and 8.6 for swap)

![Image](https://github.com/user-attachments/assets/3bdebb97-6b32-4aed-9eeb-ae90da5838da)

**Comment by rpgmaker** [comment]
Hi, anything else i could do to resolve this issue with 3090ti fe + cuda 12.8? Thanks

**Comment by tjruwase** [comment]
It is challenging because I am unable to repro. It is strange that execution is using > 100GB DRAM. The expected model memory footprint for a 1.5B model is ~ 30GB. 

I added extra logging to this branch: https://github.com/deepspeedai/DeepSpeed/tree/olruwase/ds_7150

Please run the repro code with this branch, and share the log portion similar to what I [shared](https://github.com/deepspeedai/DeepSpeed/issues/7150#issuecomment-2745930460) earlier.

**Comment by rpgmaker** [comment]
Thanks, Will test it out tomorrow and get back to you.

**Comment by rpgmaker** [comment]
@tjruwase , here is the ds_report

```
[2025-04-05 20:59:27,470] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
 [WARNING]  FP Quantizer is using an untested triton version (3.2.0), only 2.3.(0, 1) and 3.0.0 are known to be compatible with these kernels
fp_quantizer ........... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
gds .................... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.7
 [WARNING]  using untested triton version (3.2.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/xxxxxx/lib/python3.12/site-packages/torch']
torch version .................... 2.7.0.dev20250309+cu128
deepspeed install path ........... ['/home/xxxxxx/lib/python3.12/site-packages/deepspeed']
deepspeed info ................... 0.16.5+1ca83a6b, 1ca83a6b, olruwase/ds_7150
torch cuda version ............... 12.8
torch hip version ................ None
nvcc version ..................... 12.8
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
shared memory (/dev/shm) size .... 61.66 GB
```

**Comment by rpgmaker** [comment]
Here is the additional logs

```


[2025-04-05 21:01:02,155] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
[2025-04-05 21:01:08,025] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.16.5+1ca83a6b, git-hash=1ca83a6b, git-branch=olruwase/ds_7150
[2025-04-05 21:01:08,025] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-04-05 21:01:08,025] [INFO] [comm.py:673:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2025-04-05 21:01:08,136] [INFO] [comm.py:728:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=10.0.0.246, master_port=29500
[2025-04-05 21:01:08,136] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-04-05 21:01:08,155] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 1
[2025-04-05 21:01:08,253] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/xxxxxx/.cache/torch_extensions/py312_cu128 as PyTorch extensions root...
Emitting ninja build file /home/xxxxxx/.cache/torch_extensions/py312_cu128/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/home/xxxxxx/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -isystem /home/xxxxxx/lib/python3.12/site-packages/torch/include -isystem /home/xxxxxx/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /usr/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/xxxxxx/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
[2/3] c++ -MMD -MF cpu_adam_impl.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/home/xxxxxx/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -isystem /home/xxxxxx/lib/python3.12/site-packages/torch/include -isystem /home/xxxxxx/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /usr/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/xxxxxx/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/cpu_adam_impl.cpp -o cpu_adam_impl.o 
[3/3] c++ cpu_adam.o cpu_adam_impl.o -shared -lcurand -L/usr/local/cuda/lib64 -L/home/xxxxxx/lib/python3.12/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o cpu_adam.so
Loading extension module cpu_adam...
Time to load cpu_adam op: 15.710658073425293 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000020, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2025-04-05 21:01:25,034] [INFO] [logging.py:107:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2025-04-05 21:01:25,034] [INFO] [logging.py:107:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2025-04-05 21:01:25,041] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2025-04-05 21:01:25,041] [INFO] [utils.py:59:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2025-04-05 21:01:25,041] [INFO] [logging.py:107:log_dist] [Rank 0] Creating torch.bfloat16 ZeRO stage 2 optimizer
[2025-04-05 21:01:25,041] [INFO] [stage_1_and_2.py:149:__init__] Reduce bucket size 200000000
[2025-04-05 21:01:25,041] [INFO] [stage_1_and_2.py:150:__init__] Allgather bucket size 200000000
[2025-04-05 21:01:25,041] [INFO] [stage_1_and_2.py:151:__init__] CPU Offload: True
[2025-04-05 21:01:25,041] [INFO] [stage_1_and_2.py:152:__init__] Round robin gradient partitioning: False
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/xxxxxx/deepspeed_chat.py", line 152, in <module>
[rank0]:     train_llm(model_name, data, system_prompt, output_dir)
[rank0]:   File "/home/xxxxxx/deepspeed_chat.py", line 93, in train_llm
[rank0]:     model, optimizer, _, _ = deepspeed.initialize(
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 320, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1388, in _configure_optimizer
[rank0]:     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1646, in _configure_zero_optimizer
[rank0]:     optimizer = DeepSpeedZeroOptimizer(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 407, in __init__
[rank0]:     weights_partition = get_accelerator().pin_memory(weights_partition)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/xxxxxx/lib/python3.12/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
[rank0]:     return tensor.pin_memory()
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W405 21:01:30.309646429 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

**Comment by rpgmaker** [comment]
Hi, any possible updates?

**Comment by LeonParl** [comment]
> Hi, any possible updates?

i ran into the same problem after the official (?) release of pytorch 2.7.0 in their pip source. 

there is a workaround to bypass this problem:
change stage to 3, and it works fine with the optimizer offloading set to cpu (i didn't enable the offloading of parameters through). 

hope this can help you. ;)

**Comment by rpgmaker** [comment]
Hi, Thanks for the idea. I will try it out and let you know if it works for me or not.

**Comment by rpgmaker** [comment]
@LeonParl , i still have same issue. my code is actually already using the stage 3 option

```
ds_config = {
    "train_micro_batch_size_per_gpu": 1,
    "fp16": {
        "enabled": False
    },
    "bf16": {
        "enabled": True
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "allgather_partitions": True,
        "allgather_bucket_size": 2e8,
        "overlap_comm": True,
        "reduce_scatter": True,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": True
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 1e-4,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 2e-5,
            "warmup_num_steps": 100
        }
    }
  }

```

**Comment by ciciPL** [comment]
我是256g内存，双卡4090，我也遇到同样问题，

**Comment by rpgmaker** [comment]
@ciciPL , I think this is a general issue most likely with some compatibility between deepspeed and how pytorch implement pinning. Not surprised that you are have similar issue too.

**Comment by ciciPL** [comment]
> ，我认为这是一个普遍的问题，很可能是 deepspeed 与 pytorch 实现固定的方式之间存在一定的兼容性。您也有类似的问题并不奇怪。

是的，我把offload_optimizer中pin_memory设置为false，目前可以成功运行

**Comment by cafeii** [comment]
I guess that it might be related with the usage of CPU RAM, thought I totally have no idea why it causes the bug.

I met this bug when I'm training with OpenRLHF, when I set `max_samples=10000`, everythings work, but when I set the `max_samples=1000000`,  this bug occurs.

Hope this information may help you with debugging.

**Comment by rpgmaker** [comment]
Thanks for additional detail. Still no luck so. In my example I am testing with a very small sample and batch size so it is weird that this happening.

**Comment by okdalto** [comment]
I’m experiencing the exact same issue as with @rpgmaker . Zero Stage3 didn’t help either. Based on other PRs, it seems to be a problem with Torch. Is there any other possible solution?

**Comment by okdalto** [comment]
I found a workaround. It's not a long-term solution, but I'm sharing it here for others who might encounter the same issue.

Edit the following file:
```
deepspeed/runtime/zero/stage_1_and_2.py
```

Replace this line:
```python
weights_partition = get_accelerator().pin_memory(weights_partition)
```

With this conditional block:
```python
if weights_partition.is_cuda:
    weights_partition = get_accelerator().pin_memory(weights_partition)
```

**Comment by rpgmaker** [comment]
Thanks.  Will try it out

**Comment by Bodoral** [comment]
I have the same pinning issue, can't pin more than 2GB at one step.
I'm using NVIDIA H100, is the machine you're running on manged by any workloads manger e.x. slurm ?

**Comment by rpgmaker** [comment]
@Bodoral no it is just a simple app running using just deepspeed on my 3090ti.

**Comment by smartparrot** [comment]
When I only test pin_memory() a very big variable more than 80GB,  my computer reboot directly. 
My current system is ubuntu 22.04, E5 268* CPU, 256G memory(4*64). I test this on  22.04.

When I use 24.04, I find it reports error when running pin_memory(the whole weights of llm which is very big), then I test pin_memory merely. Now  I change to 22.04, it still has pin memory issue and reboot .

Zero offload mode can not be used normally is a very big issue 

I already set ulimit -l/-u unlimited, you can use ulimit -a the watch all related variables and set if need.

I just reboot again, in this test I pin memory 40GBytes,  and monitor the memory change by numactl --hardware and free -h

<img width="1374" height="736" alt="Image" src="https://github.com/user-attachments/assets/8a861168-1f62-43f9-85c2-61cfc075e512" />

My test code:

import torch
import gc
import os
import psutil
import traceback

def print_mem(stage=""):
    """打印当前进程的 CPU 内存占用（MB）"""
    proc = psutil.Process(os.getpid())
    mem_mb = proc.memory_info().rss / 1024 / 1024
    print(f"[{stage}] CPU Mem: {mem_mb:.2f} MB")

if __name__ == "__main__":
    max_retries = 1
    print_mem("Before any allocation")

    for attempt in range(1, max_retries + 1):
        x = None
        try:
            # 分配 ~4GB (1e9 个 float32 元素)
            x = torch.randn(10* 1024 * 1024 * 1024)
            print_mem(f"After allocation (try {attempt})")

            # 直接 pin_memory，不调用外部函数
            x = x.pin_memory()
            print_mem(f"After pin_memory (try {attempt})")

            # 检查结果
            if not x.is_pinned():
                raise RuntimeError("Tensor is not pinned!")
            if not x.is_contiguous():
                raise RuntimeError("Tensor is not contiguous!")

            print(f"✅ Try {attempt} succeeded: pinned={x.is_pinned()}, contiguous={x.is_contiguous()}")
            break  # 成功，跳出重试循环

        except Exception as err:
            print(f"❌ Try {attempt} failed: {err}")
            traceback.print_exc()

        finally:
            # 无论成功与否，都要释放 x 并回收
            if x is not None:
                del x
            gc.collect()
            print_mem(f"After cleanup (try {attempt})")

    else:
        # 如果所有重试都失败，会执行这里
        print(f"⚠️ All {max_retries} attempts failed. Exiting.")

**Comment by Gario-Wang** [comment]
> [@rpgmaker](https://github.com/rpgmaker), that is interesting. Maybe the tensor size is the cause, since we already saw that 1024 size worked. Can you test a sweep of tensor sizes starting from 1024, and doubling to see the failure point?

Hi, I met a similar problem. My tensor size is 4552443392 and the error is exactly the same. However, the command 
`python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1776255488, device='cpu'))"`
does not produce any error. 
I wonder how I can resolve this issue. Thanks.

**Comment by smartparrot** [comment]
I don't know why, but my LLM traing using deepspeed zero3 offload is normal now, after I inserted another GPU , two 4090 in total, and ubuntu changed to 22.04, training framework is ms-swift, now I can do full parameter training for a 8B LLM.

**Comment by Gario-Wang** [comment]
> > [@rpgmaker](https://github.com/rpgmaker), that is interesting. Maybe the tensor size is the cause, since we already saw that 1024 size worked. Can you test a sweep of tensor sizes starting from 1024, and doubling to see the failure point?
> 
> Hi, I met a similar problem. My tensor size is 4552443392 and the error is exactly the same. However, the command `python -c "import torch; from deepspeed.accelerator import get_accelerator; get_accelerator().pin_memory(torch.empty(1776255488, device='cpu'))"` does not produce any error. I wonder how I can resolve this issue. Thanks.

Updates: I set pin_memory: false in ds_config and seems to bypass the problem.

**Comment by smartparrot** [comment]
4G is small , you can try bigger size, like 16G, 24G

**Comment by dukesun99** [comment]
Changing to zero3 solved this issue for me

**Comment by rpgmaker** [comment]
Thanks,  I will give that a try to see if it works or not.
