### ISSUE TITLE
[BUG] Qwen3 MoE  30B-A3B training stuck

### ISSUE THREAD

**Issue by hijkzzz** [deepspeedai/DeepSpeed#7461]
related issue: https://github.com/OpenRLHF/OpenRLHF/issues/1097

reproduce script

```
set -x

pip install openrlhf

deepspeed --module openrlhf.cli.train_sft \
    --max_len 2048 \
    --dataset Open-Orca/OpenOrca \
    --input_key question \
    --output_key response \
    --train_batch_size 128 \
    --micro_train_batch_size 1 \
    --max_samples 2048 \
    --pretrain Qwen/Qwen3-30B-A3B-Instruct-2507 \
    --save_path ./checkpoint/llama3-8b-sft \
    --save_steps -1 \
    --logging_steps 1 \
    --eval_steps -1 \
    --zero_stage 3 \
    --max_epochs 1 \
    --bf16 \
    --flash_attn \
    --learning_rate 5e-6 \
    --gradient_checkpointing \
    --packing_samples \
    --adam_offload \
    --ring_attn_size 1

```

logs
```
Train epoch:   0%|                                                                                                                                                              | 0/1 [00:00<?, ?it/s[rank0]:[E801 01:06:56.381097551 ProcessGroupNCCL.cpp:632] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=393216, NumelOut=1572864, Timeout(ms)=600000) ran for 600024 milliseconds before timing out.
[rank3]:[E801 01:06:56.382370929 ProcessGroupNCCL.cpp:632] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=512, NumelOut=2048, Timeout(ms)=600000) ran for 600025 milliseconds before timing out.
[rank3]:[E801 01:06:56.384721086 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 3]  failure detected by watchdog at work sequence id: 75813 PG status: last enqueued work: 75816, last completed work: 75812
[rank0]:[E801 01:06:56.384723360 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 0]  failure detected by watchdog at work sequence id: 75813 PG status: last enqueued work: 75815, last completed work: 75812
[rank3]:[E801 01:06:56.384969271 ProcessGroupNCCL.cpp:670] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank0]:[E801 01:06:56.384973319 ProcessGroupNCCL.cpp:670] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank0]:[E801 01:06:56.385519523 ProcessGroupNCCL.cpp:2106] [PG ID 0 PG GUID 0(default_pg) Rank 0] First PG on this rank to signal dumping.
[rank3]:[E801 01:06:56.385533529 ProcessGroupNCCL.cpp:2106] [PG ID 0 PG GUID 0(default_pg) Rank 3] First PG on this rank to signal dumping.
[rank2]:[E801 01:06:56.452565616 ProcessGroupNCCL.cpp:632] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=393216, NumelOut=1572864, Timeout(ms)=600000) ran for 600096 milliseconds before timing out.
[rank2]:[E801 01:06:56.452792080 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 2]  failure detected by watchdog at work sequence id: 75813 PG status: last enqueued work: 75815, last completed work: 75812
[rank2]:[E801 01:06:56.452823880 ProcessGroupNCCL.cpp:670] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank2]:[E801 01:06:56.452920351 ProcessGroupNCCL.cpp:2106] [PG ID 0 PG GUID 0(default_pg) Rank 2] First PG on this rank to signal dumping.
[rank1]:[E801 01:06:56.453133290 ProcessGroupNCCL.cpp:632] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=393216, NumelOut=1572864, Timeout(ms)=600000) ran for 600096 milliseconds before timing out.
[rank1]:[E801 01:06:56.453346210 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 1]  failure detected by watchdog at work sequence id: 75813 PG status: last enqueued work: 75815, last completed work: 75812
[rank1]:[E801 01:06:56.453378280 ProcessGroupNCCL.cpp:670] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank1]:[E801 01:06:56.453472476 ProcessGroupNCCL.cpp:2106] [PG ID 0 PG GUID 0(default_pg) Rank 1] First PG on this rank to signal dumping.
[rank3]:[E801 01:06:57.804422478 ProcessGroupNCCL.cpp:1746] [PG ID 0 PG GUID 0(default_pg) Rank 3] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 75816, last completed NCCL work: 75812.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc.
[rank3]:[E801 01:06:57.805042520 ProcessGroupNCCL.cpp:1536] [PG ID 0 PG GUID 0(default_pg) Rank 3] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank3]:[E801 01:06:57.814985064 ProcessGroupNCCL.cpp:684] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E801 01:06:57.815012877 ProcessGroupNCCL.cpp:698] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E801 01:06:57.820446145 ProcessGroupNCCL.cpp:1899] [PG ID 0 PG GUID 0(default_pg) Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=512, NumelOut=2048, Timeout(ms)=600000) ran for 600025 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:635 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f20c6d785e8 in /usr/local/lib/python3.12/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x23d (0x7f20717f8a6d in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc80 (0x7f20717fa7f0 in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f20717fbefd in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xecdb4 (0x7f2167864db4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x9caa4 (0x7f216b330aa4 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: __clone + 0x44 (0x7f216b3bda34 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=75813, OpType=_ALLGATHER_BASE, NumelIn=512, NumelOut=2048, Timeout(ms)=600000) ran for 600025 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:635 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f20c6d785e8 in /usr/local/lib/python3.12/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x23d (0x7f20717f8a6d in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc80 (0x7f20717fa7f0 in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f20717fbefd in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xecdb4 (0x7f2167864db4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x9caa4 (0x7f216b330aa4 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: __clone + 0x44 (0x7f216b3bda34 in /usr/lib/x86_64-linux-gnu/libc.so.6)

```

**Comment by hijkzzz** [comment]
@loadams

**Comment by mst272** [comment]
same

**Comment by yeshsurya** [comment]
+1 Same for me

**Comment by hijkzzz** [comment]
@loadams Hi, this is a serious bug .....

**Comment by loadams** [comment]
@hijkzzz - can you share the impacted DeepSpeed versions?

Tagging @sfc-gh-truwase as well

**Comment by hijkzzz** [comment]
latest main branch or 0.17.4 @loadams

**Comment by sfc-gh-truwase** [comment]
@hijkzzz @yeshsurya have you tried using leaf module as discussed [here](https://github.com/snowflakedb/ArcticTraining/issues/250#issuecomment-3137515349)

**Comment by hijkzzz** [comment]
> [@hijkzzz](https://github.com/hijkzzz) [@yeshsurya](https://github.com/yeshsurya) have you tried using leaf module as discussed [here](https://github.com/snowflakedb/ArcticTraining/issues/250#issuecomment-3137515349)

Thank you for your reply. This indeed solves the hanging issue. I’d like to ask if there is a general solution for MoE models, as currently each MoE model requires manually setting the leaf modules.

**Comment by hijkzzz** [comment]
Fixed by

```python
for m in self.model.modules():
    if "SparseMoeBlock" in m.__class__.__name__:
        deepspeed.utils.set_z3_leaf_modules(self.model, [m.__class__])
        print(f"Setting zero3 leaf for model on class with name: {m.__class__.__name__}")
        break
```

**Comment by sfc-gh-truwase** [comment]
@hijkzzz thanks for a sharing possible fix for DeepSpeed to automatically mark leaf modules. Perhaps, we could add a ds_config option that is a list of relevant module names to pattern-match for this purpose. 

```json
           "zero_optimization":  {
              "stage" : 3,
             "leaf_module_names": "['SparseMoeBlock', ....]"
          }
```

@hijkzzz, do you think this would be helpful?

@tohtana what do you think?

**Comment by tohtana** [comment]
Hi @sfc-gh-truwase, @hijkzzz,

We could add the setting though the API currently expects a *class*, not a class name. We will need to require users to specify the fully qualified name including its package. We may also want to discuss whether the leaf module setting in ds config is better than @hijkzzz's approach.

Another approach is to have the default list of MoE classes. But this adds the dependency on HF's class names in DeepSpeed.

**Comment by sfc-gh-sbekman** [comment]
@tohtana, ds_init could traverse the sub-modules, get the name of each class and match to the class name listed in `leaf_module_names`, no? 

edit: which is exactly what @hijkzzz's workaround does, so just adding it to ds_init

**Comment by tohtana** [comment]
Hi @sfc-gh-sbekman,

Sure, we can do it. We just need to decide some details like how to handle the same class names (or we could accept only the class name with the package)

**Comment by sfc-gh-sbekman** [comment]
if you're worried about having `submoduleA.Foo` and `submoduleB.Foo` conflict, perhaps we could support both, short and fully qualified names?

So that normally a short name will be used: `SparseMoeBlock`, but if there is a duplicated class name belonging to a different fully qualified path, the user could disambiguate by listing `transformers.models.qwen3_moe.SparseMoeBlock` string?

The automation could also add a dict of seen names and their parent module and flag to the user if it detects 2 identical classes at different parent modules and one of those classes was listed in leaves?

**Comment by sfc-gh-sbekman** [comment]
@hijkzzz, so were you able to run `Qwen/Qwen3-30B-A3B-Instruct-2507` on a multi-gpu setup? I used your recipe and there is a progress of layers running, but with 8 gpus then it hangs again in the `backward` of the last layer. Specifically `py-spy` shows all gpus stuck in `_engine_run_backward`

```
$ pgrep -P $(pgrep -P $(pgrep -n arctic_training) | tail -1) | xargs -I {} py-spy dump --pid {} | grep -A2 MainThread
Thread 31833 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31834 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31835 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31836 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31837 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31838 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31839 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
--
Thread 31840 (idle): "MainThread"
    _engine_run_backward (torch/autograd/graph.py:829)
    backward (torch/autograd/__init__.py:354)
```

**Comment by sfc-gh-sbekman** [comment]
The unusual thing is that all 8 gpus are stuck in the same place
```
    _engine_run_backward (torch/autograd/graph.py:829)
```
which is the first line of the try block:
```
    try:
        return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
            t_outputs, *args, **kwargs
        )  # Calls into the C++ engine to run the backward pass
```

so it's stuck somewhere in the C++ land.

`strace` shows some futex lock.

```
$ strace -p 31839
strace: Process 31839 attached
futex(0x90baa6a8, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY^Cstrace: Process 31839 detached
```

**Comment by sfc-gh-sbekman** [comment]
The problem seems to have to do with the size of the models.

I tried a few more much smaller models. These work fine:
- `snake7gun/tiny-random-qwen3moe` (tiny)
- `DavidAU/Qwen3-MOE-4x0.6B-2.4B-Writing-Thunder`

This one `DavidAU/Qwen3-MOE-6x1.7B-10.2B-Shining-Madness-Uncensored` works the first iteration, but hangs on the first layer of the first iteration: I get 3 different states:

4 processes in
```
    synchronize (torch/cuda/streams.py:231)
    fetch_sub_module (deepspeed/runtime/zero/partitioned_param_coordinator.py:335)
    decorate_context (torch/utils/_contextlib.py:120)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    _fn (torch/_dynamo/eval_frame.py:929)
    pre_sub_module_forward_function (deepspeed/runtime/zero/parameter_offload.py:473)
    decorate_context (torch/utils/_contextlib.py:120)
    _pre_forward_module_hook (deepspeed/runtime/zero/parameter_offload.py:298)
    _fn (torch/_dynamo/eval_frame.py:929)
    inner (torch/nn/modules/module.py:1816)
    _call_impl (torch/nn/modules/module.py:1879)
    _wrapped_call_impl (torch/nn/modules/module.py:1773)
    forward (arctic_training/model/qwen3_moe/modeling_qwen3_moe.py:167)
```

1 process in:
```
    forward (deepspeed/runtime/zero/linear.py:64)
    decorate_fwd (torch/amp/autocast_mode.py:517)
    apply (torch/autograd/function.py:576)
    zero3_linear_wrap (deepspeed/runtime/zero/linear.py:116)
    forward (torch/nn/modules/linear.py:125)
    inner (torch/nn/modules/module.py:1827)
    _call_impl (torch/nn/modules/module.py:1879)
    _wrapped_call_impl (torch/nn/modules/module.py:1773)
    forward (arctic_training/model/qwen3_moe/modeling_qwen3_moe.py:166)
    wrapped_func (transformers/utils/deprecation.py:172)
    inner (torch/nn/modules/module.py:1827)
    _call_impl (torch/nn/modules/module.py:1879)
    _wrapped_call_impl (torch/nn/modules/module.py:1773)
    forward (arctic_training/model/qwen3_moe/modeling_qwen3_moe.py:346)
```

and 3 in:
```
    get_lst_from_rank0 (deepspeed/runtime/zero/utils.py:76)
    assert_ints_same_as_other_ranks (deepspeed/runtime/zero/utils.py:88)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    reset_step (deepspeed/runtime/zero/partitioned_param_coordinator.py:237)
    _fn (torch/_dynamo/eval_frame.py:929)
    _start_of_forward_hook (deepspeed/runtime/zero/parameter_offload.py:251)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    inner (torch/nn/modules/module.py:1816)
    _call_impl (torch/nn/modules/module.py:1879)
    _wrapped_call_impl (torch/nn/modules/module.py:1773)
    forward (deepspeed/runtime/engine.py:2131)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    _call_impl (torch/nn/modules/module.py:1784)
    _wrapped_call_impl (torch/nn/modules/module.py:1773)
    loss (arctic_training/trainer/sft_trainer.py:52)
```

**Comment by sfc-gh-sbekman** [comment]
going back to `Qwen/Qwen3-30B-A3B-Instruct-2507` I used `cuda-gdb`+core-dump to get where it was hanging in `_engine_run_backward` and it's:

```
#11 0x00007f2451c79a7c in cudaMemcpyAsync ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#12 0x00007f23da8a0186 in at::native::copy_kernel_cuda(at::TensorIterator&, bool) ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so
#13 0x00007f24315918b3 in at::native::copy_impl(at::Tensor&, at::Tensor const&, bool) [clone .isra.0] ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#14 0x00007f2431593197 in at::native::copy_(at::Tensor&, at::Tensor const&, bool) ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#15 0x00007f24357ecaec in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool), &torch::ADInplaceOrView::copy_>, at::Tensor&, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool> >, at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool) ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#16 0x00007f24357edc4c in torch::autograd::VariableType::(anonymous namespace)::copy_(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool)
    () from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#17 0x00007f24322493e7 in at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool) ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#18 0x00007f244442260c in torch::autograd::THPVariable_copy_(_object*, _object*, _object*) ()
   from /home/yak/miniconda3/envs/dev/lib/python3.12/site-packages/torch/lib/libtorch_python.so
#19 0x0000000000545869 in method_vectorcall_VARARGS_KEYWORDS (func=<optimized out>, args=0x7f2452a22df8, nargsf=<optimized out>,
    kwnames=<optimized out>) at /usr/local/src/conda/python-3.12.11/Objects/descrobject.c:365
```

so some async copy is hanging, let's do `export CUDA_LAUNCH_BLOCKING=1`

**Comment by sfc-gh-sbekman** [comment]
so now we can use py-spy again:

3 processes in:
```
Thread 33550 (active): "MainThread"
    all_reduce (torch/distributed/distributed_c10d.py:2924)
    wrapper (torch/distributed/c10d_logger.py:81)
    all_reduce (deepspeed/comm/torch.py:170)
    all_reduce (deepspeed/comm/comm.py:654)
    log_wrapper (deepspeed/comm/comm.py:118)
    complete_grad_norm_calculation_for_cpu_offload (deepspeed/runtime/zero/stage3.py:1467)
    _get_norm_groups (deepspeed/runtime/zero/stage3.py:1897)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    step (deepspeed/runtime/zero/stage3.py:2120)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    _take_model_step (deepspeed/runtime/engine.py:2365)
    step (deepspeed/runtime/engine.py:2470)
    step (arctic_training/trainer/trainer.py:398)
```

5 processes in:
```
Thread 33549 (active): "MainThread"
    reduce_scatter_tensor (torch/distributed/distributed_c10d.py:4450)
    wrapper (torch/distributed/c10d_logger.py:81)
    reduce_scatter_tensor (deepspeed/comm/torch.py:290)
    reduce_scatter_tensor (deepspeed/comm/comm.py:302)
    log_wrapper (deepspeed/comm/comm.py:118)
    reduce_scatter_fn (deepspeed/comm/comm.py:270)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    _torch_reduce_scatter_fn (deepspeed/runtime/comm/coalesced_collectives.py:23)
    reduce_scatter_coalesced (deepspeed/runtime/comm/coalesced_collectives.py:205)
    decorate_context (torch/utils/_contextlib.py:120)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    __avg_scatter_grads (deepspeed/runtime/zero/stage3.py:1408)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    __reduce_and_partition_ipg_grads (deepspeed/runtime/zero/stage3.py:1333)
    decorate_context (torch/utils/_contextlib.py:120)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    independent_gradient_partition_epilogue (deepspeed/runtime/zero/stage3.py:1147)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    overlapping_partition_gradients_reduce_epilogue (deepspeed/runtime/zero/stage3.py:1173)
    allreduce_gradients (deepspeed/runtime/engine.py:2186)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    _backward_epilogue (deepspeed/runtime/engine.py:2235)
    backward (deepspeed/runtime/engine.py:2299)
    wrapped_fn (deepspeed/utils/nvtx.py:20)
    backward (arctic_training/trainer/trainer.py:378)
```

**Comment by tohtana** [comment]
Hi @sfc-gh-sbekman,
Thank you for the investigation. I wonder if the order of allgather/allreduce could be broken in some situation (e.g. dummy gradient of unused expert is not properly created). Can we validate the order of the communication collectives?

**Comment by sfc-gh-truwase** [comment]
@tohtana thanks for the response. I think your suggestion of imbalanced gradient cause might be correct. In the meantime, I created PR to improve the error detection.

**Comment by sfc-gh-sbekman** [comment]
to update on the debug Tunji and I did yesterday - we found that using a reduction bucket that is larger than the model so that no grad reductions happen during backward + `overlap_comm: false` allows the first iteration to succeed, but then it hangs in the first forward of the second iteration in the same way as here  https://github.com/deepspeedai/DeepSpeed/issues/7461#issuecomment-3229772472
